-- 简单的子查询测试
DROP TABLE IF EXISTS t1;
DROP TABLE IF EXISTS t2;

CREATE TABLE t1(id INT, name CHAR(10));
CREATE TABLE t2(id INT NOT NULL);

INSERT INTO t1 VALUES(1, 'a');
INSERT INTO t1 VALUES(2, 'b');
INSERT INTO t1 VALUES(3, 'c');

INSERT INTO t2 VALUES(1);
INSERT INTO t2 VALUES(2);
INSERT INTO t2 VALUES(3);

-- 直接测试子查询
SELECT * FROM t1 WHERE id IN (SELECT id FROM t2);


